# **context控制**

## **概述**

Larva提供了context机制来实现对业务层面的任务处理代码的控制，这个概念和Go中的context非常类似（实际也是基于Go的context包来做的），
但在使用方式上和Go有所差别

context是Larva代码执行中属于当前代码流程的一个隐式对象，可以通过`fiber.is_canceled`模块的接口检查context是否被取消，
一个任务代码如果发现当前context已经被取消，则可提前结束对应的业务流程，一般做法是直接调用`fiber.throw_if_canceled`，
这个接口会在当前context取消的时候抛出`fiber.Canceled`异常

例：
```
void deal_with_task()
{
    //每个步骤完成的时候检查是否被取消
    step1();
    fiber.throw_if_canceled();
    step2();
    fiber.throw_if_canceled();
    while (true)
    {
        step3();
        if (fiber.is_canceled())
        {
            //这里可以做一些自己的流程清理工作

            fiber.throw_if_canceled(); //context被取消后是无法恢复为正常状态的，所以这句等于是直接抛fiber.Canceled
        }
    }
}
```
可以看到context实际相当于一个状态值，可以被设置为取消状态，其对应的代码流程可自行在合适和安全的位置去检查状态并做对应处理，
这是一个建议性取消而非强制性的

Larva的标准库中的常见阻塞操作（如`Chan`收发操作、`net`模块的各种网络通讯的收发操作、`sync`模块的锁的加锁操作等）都会受到context影响，
如果在阻塞中context被取消了，则抛出`fiber.Canceled`异常

## **context的创建**

context的创建遵循如下规则：
1. 程序启动后，主fiber创建自己的context，之后的初始化、调用main函数等流程都是在这个context中
1. 创建普通fiber的时候，新fiber会创建自己的context并用其调用fiber入口函数或方法
1. 创建worker fiber的时候，会创建一个继承创建者当前context的新context，并用其调用fiber入口函数或方法
1. 通过`fiber.call_with_cancel(callee)`可创建一个继承当前context的新context，并用其调用传入的`callee`，一个`Callable`对象
1. 通过`fiber.call_with_timeout(timeout, callee)`可创建一个继承当前context并且带超时的新context，并用其调用传入的`callee`，一个`Callable`对象

## **context的继承**

如上面创建规则所述，context之间可以有继承关系，当一个context被取消时，所有直接或间接继承它的context都会被取消

例如：当前代码流程创建了若干个worker fiber去并发执行任务，若当前流程的context被取消，则所有worker及它们衍生出的worker、流程的context都会被取消

## **context的取消**

context的取消有几种情况

1. 所对应的流程结束

    虽然流程结束后自然不会再用到当前context了，但是这个事件会取消所有继承它的context，也就是说相当于可以让子流程感知到父流程的结束

    结合上面的创建规则，这里的“流程结束”只有以下几种情况：
    1. fiber结束，取消当前fiber的context
    1. `fiber.call_with_cancel`或`fiber.call_with_timeout`结束，即它们调用的`Callable`对象的调用以正常`return`或抛出异常的形式结束，
    都会取消掉对应的context

1. 通过`fiber.call_with_timeout(timeout, callee)`执行`callee`的流程中，若指定的超时时间到了，则context被取消

1. 如果是直接或间接继承了其他context，则后者被取消的时候当前context也被取消

因此，context的取消是由代码流程和内部机制触发的，通过正常手段是无法直接取消的

如上所述，context的状态从正常变为已取消后就不能再变回正常了，如果一个context经历了上面多个情形的取消也是没问题的（例如先超时被取消然后`fiber.call_with_timeout`结束的时候又被取消一次），多次取消操作和一次的效果相同

### **fiber.Canceled异常**

通过`fiber.throw_if_canceled()`将会在当前context被取消时抛出`fiber.Canceled`异常，除了`Throwable`接口规定的`str`方法外，
还可以调用其他接口来获取一些详细信息：
```
public class Canceled
{
    /*
    判断是否因为对应context超时而被取消
    注意是对应context是否超时，如果是因为父context超时取消而因为继承关系被取消，也是返回false
    */
    public bool is_timeout()
    {
        实现略
    }

    实现略
}
```

## **场景示例**

1. 业务处理流程限时

    在服务器开发中，常采用“接收请求->处理->回复”的方式来处理业务请求，如果处理过程较长，考虑到请求发送方不可能无限制等待，一般会有个超时，
    例如发送方发请求后等待回复最多1秒钟，那么服务器的处理时长超出1秒的时候后续流程就无意义了

    服务器的一个处理流程往往比较复杂，例如有三次和数据库等后端的通讯，如果每一步操作单独计算超时就会有个如何分配超时时间的问题，
    由于操作时长和具体请求、线上环境都有关系，所以并不能很好决定时间的分配

    一般的做法是给服务器的请求处理加一个总的时间限制，具体到流程中的每个操作则可以有自己的超时，或沿用总流程的超时

    例：
    ```
    void deal_with_req(req)
    {
        fiber.call_with_timeout(1 /*假设总流程1秒超时*/, [-]{
            step1();
            fiber.call_with_timeout(0.3 /*第二步操作在300毫秒内必须完成*/, [-]{
                step2();
            });
            fiber.call_with_timeout(0.8 /*第三步操作在800毫秒内必须完成*/, [-]{
                step3();
            });
        });
    }
    ```
    这个例子是一个简单的请求处理的流程代码，可以看到分为三个操作步骤，我们限制了总流程需要在1秒内完成，内部的第二、三流程则有自己的超时时间，
    即若第二步超过300毫秒，或第三步超过800毫秒，或总流程超过1秒，都会取消对应的context，由于继承关系，
    外层`fiber.call_with_timeout`的context取消时也意味着内层两个context被取消，而内层context被取消后只要正常抛出`fiber.Canceled`异常，
    就会上抛到`deal_with_req`外部，此时外层context自然也因为流程结束而取消了，从`deal_with_req`的调用者看来就是流程处理出现异常

1. 结束无需等待的worker fiber

    在流程代码中可能开启若干worker去并发地做任务，而且这些任务并不需要等待执行结果，例如非关键任务，或一个随着当前流程运行的协作fiber等，
    在流程结束后它们就没必要继续运行了，可以通过context去结束它们

    *Note*：这里的“结束worker fiber”是一种通俗说法，本质当然是指“通知worker自行结束”

    例：
    ```
    void f()
    {
        step1();
        
        fiber.call_with_cancel([-]{
            //开启一个worker来并发执行某些任务
            fiber.start_worker([-]{
                略
            });

            step2();
        });

        step3();
    }
    ```
    这个例子中，我们需要一个worker fiber来伴随着第二个步骤的执行，比如我们可能让这个worker去监控`step2()`流程中的一些情况然后在后台记录日志等，
    当第二步结束时这个worker就没用了，应该及时结束掉，所以用`fiber.call_with_cancel`来构建一个流程，流程中创建的worker继承这个流程的context，
    这样当流程结束的时候，worker的context也会被取消，当然了，如果所继承的context，即函数`f`所在的context被取消了，也会影响到这里

    *Note*
    
    * 显然，如果不创建worker fiber，单纯调用`fiber.call_with_cancel`执行`Callable`对象的代码是没有实际意义的，
    因为创建出的context只有执行结束后才被取消，这样做就等同于直接调用

    * 在‘3.6.并发模型’中讲过，worker如果因为异常结束，异常是保存在`fiber.Worker`对象实例中，由于这里忽略了`fiber.start_worker`返回的worker对象，
    所以相当于忽略了worker可能的异常

    * 由于context的取消是要worker自行检查并退出，所以实际上在`fiber.call_with_cancel`退出后，worker还可能在运行，
    这个机制只能保证让无意义的worker尽早结束，如果需要保证`step2()`结束后worker也结束，需要自行实现同步机制

1. 多worker并发处理的限时

    在有的流程中，不同步骤之间没有依赖关系，可以并行处理，例如向后端三个数据库发送查询请求，分别查到结果再汇总等场景

    例：
    ```
    void f()
    {
        fiber.call_with_timeout(1, [-]{
            var w1 = fiber.start_worker([-]{
                step1()
            });
            var w2 = fiber.start_worker([-]{
                step2()
            });
            deal_with_worker_exc(w1.wait());
            deal_with_worker_exc(w2.wait());
        });
    }
    ```
    例子中的两个步骤是分别在两个worker fiber中并发执行，主流程通过`wait`来依次等待它们执行完毕，如果这个流程的context因为超时或其他原因被取消，
    则`wait`的阻塞会抛出`fiber.Canceled`异常，流程结束后两个worker都会被取消
